name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Azure VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 52.140.100.215  # Replace with your Azure VM's public IP address
          username: admin01  # Replace with your Azure VM username
          password: Pass123456789  # Replace with your Azure VM password
          port: 22
          script: |
            cd /path/to/your/nodejs/app
            git pull origin main  # Pull latest changes from GitHub
            docker-compose down   # Stop existing containers if using docker-compose
            docker-compose up -d  # Start updated containers
