name: Test SSH Connectivity

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub UI

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Use your Azure password stored in secrets
          script: |
            echo "SSH connection successful!"
