name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Azure VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          script: |
            cd /path/to/your/nodejs/app
            git pull origin main  # Pull latest changes from GitHub
            docker-compose down   # Stop existing containers if using docker-compose
            docker-compose up -d  # Start updated containers
